name: run-login
on: 
  repository_dispatch: 
    types: [enter-code]


jobs:
  complete-code:
    runs-on: ubuntu-latest
    steps:
      - name: Show the code we got
        run: echo "Got Code ${{ github.event.client_payload.code }}"
